/* eslint-disable */
import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "../../components/nav";
import Footer from "../../components/footer";

import { useRouter } from "next/router";
import { ToastContainer, toast } from 'react-toastify';


import { useState } from "react";

const Home: NextPage = () => {
    const [searchText, setSearchText] = useState("");
    const [indexOption, setIndexOption] = useState("bert")
    const router = useRouter();

    const handleOptionChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setIndexOption(event.target.value);
    };


    const handleSubmit = async () => {
        if (searchText === "") {
            toast.error("Please enter some ingredients", {
                position: toast.POSITION.TOP_RIGHT
            });
            return;
        }
        else {
            let res;
            const mp: any = {}
            mp["searchText"] = searchText;
            mp["indexOption"] = indexOption;
            //do a get request to the backend with mp in the body
            const requestOptions: RequestInit = {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(mp),
            };

            await fetch('http://169.235.31.46:8888/search', requestOptions)
                .then(response => response.json())
                .then(data => {
                    res = data;
                    res["indexOption"] = indexOption;

                    router.push({
                        pathname: '/results',
                        query: { data: JSON.stringify(res) },
                    });
                })
                .catch(error => console.error(error));
        }
    }

    return (
        <>
            <Head>
                <title>ReciPy</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#17131c] to-[#16183a]">
                {/* <NavBar /> */}
                <div className="container flex flex-col items-center justify-center gap-12 p-4">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] ">
                        Reci<span className="text-[hsl(131,65%,63%)]">Py</span>
                    </h1>

                    <p className="text-2xl text-white">
                        Enter the name of a dish or ingredient to get started
                    </p>


                    <div className="flex items-center">
                        <div className="flex  rounded">
                            <input
                                type="text"
                                className="block w-full px-4 py-2 bg-white border rounded-md focus:border-purple-400 focus:ring-purple-300 focus:outline-none focus:ring focus:ring-opacity-40"
                                placeholder="Search..."
                                value={searchText}
                                onChange={(e) => setSearchText(e.target.value)}
                            />

                            <button className="px-4 text-white bg-[hsl(131,65%,63%)] ml-1 border-l rounded " onClick={handleSubmit}>
                                Search
                            </button>
                        </div>

                    </div>
                    <div className="flex items-center mt-6">
                        <p className="mr-4 text-white">Index option:</p>
                        <div className="flex items-center">
                            <label className="inline-flex items-center">
                                <input
                                    type="radio"
                                    value="bert"
                                    checked={indexOption === "bert"}
                                    onChange={handleOptionChange}
                                    className="form-radio text-[hsl(131,65%,63%)]"
                                />
                                <span className="ml-2 text-white">BERT</span>
                            </label>
                            <label className="inline-flex items-center ml-6">
                                <input
                                    type="radio"
                                    value="lucene"
                                    checked={indexOption === "lucene"}
                                    onChange={handleOptionChange}
                                    className="form-radio text-[hsl(131,65%,63%)]"
                                />
                                <span className="ml-2 text-white">Lucene</span>
                            </label>
                        </div>
                    </div>
                </div>
                <ToastContainer />

                {/* <Footer /> */}
            </main>
        </>
    );
};

export default Home; 0
